### ISSUE TITLE
如果加个网络小说加载功能，这个项目更完美了

### ISSUE THREAD

**Issue by Sabirjan** [dengzemiao/DZMeBookRead#22]
就是 获取项目目录，下载制定的章节，解析显示。缓存。批量下载的。 期待ing....
谢谢您的分享！

**Comment by dengzemiao** [comment]
@Sabirjan 可以看 issue 里面的这个问题回答 网络小说的一些问题 ，其实我也是为了不要代码太乱 ，只要理解了我的思路完全可以很轻松的就加入网络，网络阅读比本地相对简单

**Comment by dengzemiao** [comment]
@Sabirjan 因为加入网络的话很多数据结构会不一样， 没个公司都有自己的结构，到时候会导致别人拿到之后要大改大把的删代码，所以还不如给个原始点的  自己都可以往里面加 会更方便 也不需要删除太多的不必要的东西

**Comment by Sabirjan** [comment]
我已经老版本改成网络小说的。这个新版本我看代码更清晰，有点懒修改 ，呵呵。感谢您的分享！
