### ISSUE TITLE
集成遇到这种问题，不知怎么解决While emitting SIL for

### ISSUE THREAD

**Issue by likaiwork** [dengzemiao/DZMeBookRead#34]
集成遇到这种问题，不知怎么解决

1.	While emitting SIL for 'layoutSubviews()' at /Users/jordan/Documents/OtherProject/2018Git/QuanZhiGaoShou/Master/DZMeBookRead/other/custom/DZMSegmentedControl.swift:246:14
2.	While silgen emitFunction SIL function "@_T06Master19DZMSegmentedControlC14layoutSubviewsyyF".
 for 'layoutSubviews()' at /Users/jordan/Documents/OtherProject/2018Git/QuanZhiGaoShou/Master/DZMeBookRead/other/custom/DZMSegmentedControl.swift:246:14

1.	While emitting SIL for 'layoutSubviews()' at /Users/jordan/Documents/OtherProject/2018Git/QuanZhiGaoShou/Master/DZMeBookRead/menuUI/DZMRMLeftView.swift:100:14
2.	While silgen emitFunction SIL function "@_T06Master13DZMRMLeftViewC14layoutSubviewsyyF".
 for 'layoutSubviews()' at /Users/jordan/Documents/OtherProject/2018Git/QuanZhiGaoShou/Master/DZMeBookRead/menuUI/DZMRMLeftView.swift:100:14

**Comment by dengzemiao** [comment]
你是一集成就有 还是自己后面改了之后出现了这个问题。 我这边测试了集成没有发现这个问题

**Comment by dengzemiao** [comment]
网上有查到是xcode编译问题，没有确认过
