### ISSUE TITLE
有声阅读

### ISSUE THREAD

**Issue by ZJF-Coder** [dengzemiao/DZMeBookRead#45]
请问开发者可以自行添加有声阅读功能么？作者有没有预留一些接口之类的（作者是否有预留：获取当前小说内容页面的文字功能）？

**Comment by dengzemiao** [comment]
@ZJF-Coder 有的 可以随时获取当前展示的这一页内容 以及章节信息

**Comment by dengzemiao** [comment]
@ZJF-Coder 同时也可以判断是否还有有上一页或下一页，上一章或下一章，获取他们的页或章内容
