### ISSUE TITLE
怎么去掉书籍首页

### ISSUE THREAD

**Issue by liuqingtong** [dengzemiao/DZMeBookRead#47]
请教下，怎么去掉书籍首页？我用的是最新版的，V1.3

**Comment by dengzemiao** [comment]
@liuqingtong 看我 DZMReadParser.swift 里面的 if isFirstChapter { // 第一页为书籍页面 } 
其实首页我只是用 DZM_READ_BOOK_HOME_PAGE 这个全局变量进行判断，你不设置这个 DZM_READ_BOOK_HOME_PAGE 就没有首页，你如果需要首页 那你就仿照我的设置 
pageModel.range = NSMakeRange(DZM_READ_BOOK_HOME_PAGE, 1) 就可以指定这一页为首页展示样式
