### ISSUE TITLE
仿真翻页和滚动翻页的时候，右滑返回没有禁止掉

### ISSUE THREAD

**Issue by liuqingtong** [dengzemiao/DZMeBookRead#49]
大佬，阅读页仿真翻页和滚动翻页的时候，右滑返回没有禁止，请问能禁止吗？现在是第一页直接能右滑返回，离开阅读页。

**Comment by dengzemiao** [comment]
@liuqingtong  肯定可以静止返回啊  DZMReadMenu.swift 不是有加禁止返回么，它是基于 FDFullscreenPopGesture 这个导航栏库的 我是有加的呀！

 // 隐藏导航栏
 vc.fd_prefersNavigationBarHidden = true
        
// 禁止手势返回
vc.fd_interactivePopDisabled = true
