### ISSUE TITLE
能不能优化，加载速度越来越慢！

### ISSUE THREAD

**Issue by Sabirjan** [dengzemiao/DZMeBookRead#7]
解析出来第一章就会要你进入阅读, 别的章节都在后台解析。
能不能优化，现在加载速度慢，有点文字多点的文章就卡死了。。。。
我把他改成网络图书的，但是基本解析的地方没改。。。。
怎么优化，那个类，请教一下，谢谢！

**Comment by Sabirjan** [comment]
![image](https://cloud.githubusercontent.com/assets/7404699/23888571/a6ab6318-08c3-11e7-8a93-2fcb63fcbe57.png)

**Comment by Sabirjan** [comment]
加载目录的时候，我把这一行注释，我觉得速度差不多提高了几倍...
但是还是有些地方存在问题的感觉

**Comment by dengzemiao** [comment]
没明白你的需求 我自己这边是网络小说 本地小说倒还没做 解析一章之后 别的章节进入后台解析 会出问题？

**Comment by Sabirjan** [comment]
我自己解决了...谢谢，如果可以的话，把网络小说部分能不能分享出来！
现在项目都是网络小说...
